export enum CompanyWorkExperience {
    DOES_NOT_MATTER = "DOES_NOT_MATTER",
    LESS_THAN_ONE_YEAR = "LESS_THAN_ONE_YEAR",
    FROM_ONE_TO_THREE_YEARS = "FROM_ONE_TO_THREE_YEARS",
    FROM_THREE_TO_SIX_YEARS = "FROM_THREE_TO_SIX_YEARS",
    MORE_THAN_SIX_YEARS = "MORE_THAN_SIX_YEARS",
}
