export enum EmployeeStatus {
    DOES_NOT_MATTER = "DOES_NOT_MATTER",
    ON_MATERNITY_LEAVE = "ON_MATERNITY_LEAVE",
    ON_VACATION = "ON_VACATION",
    ON_SICK_LEAVE = "ON_SICK_LEAVE",
    ACTIVE = "ACTIVE"
}
